# Generated by Django 3.2.3 on 2021-05-22 05:27

import os

from django.core.exceptions import ImproperlyConfigured
from django.db import migrations


def get_env_var(var: str):
    try:
        return os.environ[var]
    except KeyError:
        raise ImproperlyConfigured(f'Set the "{var}" environment variable.')


def create_superuser(apps, schema_editor):
    su_username = get_env_var("SU_USERNAME")
    su_password = get_env_var("SU_PASSWORD")
    User = apps.get_model("accounts", "User")

    User.objects.create_superuser(username=su_username, password=su_password)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
